# Generated by Django 3.2.2 on 2021-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='from_time_zone',
            field=models.TextField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='classes',
            name='img_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='to_time_zone',
            field=models.TextField(default='', max_length=16),
        ),
    ]
