# Generated by Django 3.2.2 on 2021-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210510_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
