# Generated by Django 3.2.2 on 2021-05-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_classes_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='author',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='classes',
            name='from_time_zone',
            field=models.TextField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='classes',
            name='to_time_zone',
            field=models.TextField(default='', max_length=8),
        ),
    ]
